### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by nigredon1991** [kingnothinq/Parser#4]
pip freeze > requirements.txt

Не храни venv в гите. В нормальных случаях это не требуется.

**Comment by nigredon1991** [comment]
Добавь ещё файл 
.gitignore
В нём запиши, что не должно попадать в коммиты.
Что-то типа такого:
https://github.com/github/gitignore/blob/master/Python.gitignore

**Comment by kingnothinq** [comment]
fixed
